# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('City', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=100)),
                ('Sport', models.CharField(max_length=40)),
            ],
        ),
    ]
