# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='groupdetails',
            name='grpid',
            field=models.IntegerField(default=0, max_length=32, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
