# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_auto_20161025_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetails',
            name='grpid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
