# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_auto_20161025_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetails',
            name='EndTime',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='groupdetails',
            name='StartTime',
            field=models.IntegerField(max_length=10),
        ),
    ]
